# Neural network

In [1]:
from sklearn.datasets import load_boston
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import time

In [2]:
boston = load_boston()

In [3]:
boston.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR'])

In [4]:
df = pd.DataFrame(pd.concat([pd.DataFrame(boston['data']), pd.DataFrame(boston['target'])], axis = 1)) 
df.columns = list(boston['feature_names']) + ['target']


In [5]:
df_nn = df[['LSTAT', 'target']]
x = np.array(df_nn['LSTAT']).reshape(506, 1)
y = np.array(df_nn['target']).reshape(506, 1)
test = np.concatenate([x, y], axis = 1)

FIND OUT ABOUT NAME SPACES FOR FUNCTIONS IN CLASSES FOR ACTIVATION FUNCTIONS

In [6]:
class NeuralNetwork(object):
    
    def __init__(self, x, y, learning_rate = 0.01):
        ''' get general network architecture with 
        defining the layers, weights biases, here we assume no hidden layers for simplicity'''
        
        self.input = x
        self.target = y
        self.weights = np.random.rand(self.input.shape[1], 1)
        self.output = np.zeros(self.target.shape)
        self.learning_rate = learning_rate
        
    def mini_batches(self):
        ''' create the function to split dataset in to mini-batches and training epochs'''
        pass
        
    def activationFunction(x):
        return x
    
    def feedForward(self):
        ''' currently using the identity function as activation. Learn more about defining the activation
        within the class and change to reLU or sigmoid'''
        
        self.output = np.dot(self.input, self.weights)
    
    def backPropagation(self):
        '''Assuming no hidden layers, we only need to be concerned with the 
        derivative of the cost function. This is assuming we use a quadratic
        cost function C = (y - y_hat) ** 2
        recall that the change in weights will be :
        dL/dw = dL/dy * dy/dz * dz/dw'''
        
        d_cost = 2 * (self.output - self.target)
        d_activation = 1
        d_weights = np.dot(np.dot(self.input.T, d_cost), 1)
        self.weights -= d_weights * self.learning_rate
    
    def make_prediction(x, weights):
        return np.dot(x, weights)
    
    

In [7]:
testing = NeuralNetwork(x, y)

In [8]:
for epoch in range(50):
    testing.feedForward()
    testing.backPropagation()
    print('training NeuralNetwork... running epoch {}'.format(epoch))
    time.sleep(1)

training NeuralNetwork... running epoch 0
training NeuralNetwork... running epoch 1
training NeuralNetwork... running epoch 2
training NeuralNetwork... running epoch 3
training NeuralNetwork... running epoch 4
training NeuralNetwork... running epoch 5
training NeuralNetwork... running epoch 6
training NeuralNetwork... running epoch 7
training NeuralNetwork... running epoch 8
training NeuralNetwork... running epoch 9
training NeuralNetwork... running epoch 10
training NeuralNetwork... running epoch 11
training NeuralNetwork... running epoch 12
training NeuralNetwork... running epoch 13
training NeuralNetwork... running epoch 14
training NeuralNetwork... running epoch 15
training NeuralNetwork... running epoch 16
training NeuralNetwork... running epoch 17
training NeuralNetwork... running epoch 18
training NeuralNetwork... running epoch 19
training NeuralNetwork... running epoch 20
training NeuralNetwork... running epoch 21
training NeuralNetwork... running epoch 22
training NeuralNetwor

In [27]:
testing.weights

array([[-9.63348935e+165]])

In [10]:
#testing.make_prediction(sample, final_weights)

In [11]:
import numpy as np  
feature_set = np.array([[0,1,0],[0,0,1],[1,0,0],[1,1,0],[1,1,1]])  
labels = np.array([[1,0,0,1,1]])  
labels = labels.reshape(5,1)  

In [12]:
feature_set

array([[0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [1, 1, 0],
       [1, 1, 1]])

In [13]:
labels

array([[1],
       [0],
       [0],
       [1],
       [1]])

In [14]:
np.random.seed(42)  
weights = np.random.rand(3,1)  # This is the shape of the inputs
bias = np.random.rand(1)  # 1 because there is 1 layer only
lr = 0.05

In [15]:
def sigmoid(x):  
    return 1/(1+np.exp(-x))
def sigmoid_der(x):  
    return sigmoid(x)*(1-sigmoid(x))

In [16]:
inputs = feature_set

In [17]:
bias

array([0.59865848])

In [18]:
np.dot(feature_set, weights) + bias # sum of W * I + b
# you get the activation value for each of the datapoints 
# Running the whole dataset at once

array([[1.54937279],
       [1.33065243],
       [0.9731986 ],
       [1.92391291],
       [2.65590685]])

In [19]:
XW = np.dot(feature_set, weights) + bias
sigmoid(XW)

# Sigmoid applied to sums all at once

array([[0.82482312],
       [0.79094853],
       [0.72575659],
       [0.87257414],
       [0.93437412]])

In [20]:
z  = sigmoid(XW)
z - labels

# Error for all datapoints at once
# Loop is for?

array([[-0.17517688],
       [ 0.79094853],
       [ 0.72575659],
       [-0.12742586],
       [-0.06562588]])

In [21]:
error = z- labels
error.sum()

# This error is the total error for the whole dataset?

1.1484765089981492

In [22]:
dcost_dpred = error
sigmoid_der(z)
# RECALL error is squared for each datapoint 
# so MSE is the error for whole dataset?

array([[0.21187385],
       [0.21464285],
       [0.21976804],
       [0.20785969],
       [0.20249263]])

In [23]:
dpred_dz = sigmoid_der(z)
dcost_dpred * dpred_dz

array([[-0.0371154 ],
       [ 0.16977145],
       [ 0.1594981 ],
       [-0.0264867 ],
       [-0.01328876]])

In [24]:
z_delta = dcost_dpred * dpred_dz
# slope = input * dcost_dpred * dpred_dz
# z delta is 2 parts of the slope only
feature_set.T

array([[0, 0, 1, 1, 1],
       [1, 0, 0, 1, 1],
       [0, 1, 0, 0, 1]])

In [25]:
inputs = feature_set.T
lr * np.dot(inputs, z_delta)
#weights -= lr * np.dot(inputs, z_delta) 

array([[ 0.00598613],
       [-0.00384454],
       [ 0.00782413]])

In [26]:
for num in z_delta:
    bias -= lr * num